### PR TITLE
Allows shebang propagation [closes #6]

### LINKED ISSUE #6: Binary execution issues due to shebang
Hey there, it's me again !

Due to 6476a7777ae1f5e265d9db96d4edf7200289c8ae, there could be an issue when executing directly a Stickytape-d resulting output.
A Python 3 compatible-only script may be executed against a Python 2 interpreter (on distributions having Python 2 as the default interpreter).

Maybe the code should contain one more condition to correctly figure out whether it should used `#!/usr/bin/env python` or `#!/usr/bin/env python3` ?

I think reverting the commit referenced above should work, but I guess you had a reason to implement it.

Bye :wave:

### PR DESCRIPTION
**Pull request by HorlogeSkynet**
Hey @mwilliamson, I tried something (mainly based on a `6476a77` revert) to deal with #6. Tell me what you think about it !
Bye :wave:

### CODE REVIEW

**Comment by mwilliamson** [comment]
Hello! I think the issue with this is that in some cases, you don't want to use the existing shebang. For instance, virtualenvs create shebangs with the full path to the Python binary, which is probably not what you'd want in the final script.

**Comment by HorlogeSkynet** [comment]
Thanks for your quick feedback !

From my PoV, Stickytape _is_ (_should be_ ?) used on "final" Python scripts/modules/applications entry point that are supposed to contain (if set) a "production"-ready shebang.
That's why I think it's important that it has to be correctly propagated.

Am I wrong here ? Do you have some "not-working" examples ? Maybe we could add them as test cases then ?
Are we supposed to add to documentation something like "Users must clean their application shebang BEFORE running Stickytape" ?

Beside, do you have any idea how we could work-around this issue otherwise ?

Bye ! 👋

**Comment by mwilliamson** [comment]
The easy (but not necessarily correct) solution would be to give the user some control -- for instance, to allow them to explicitly set the shebang, or to specify that the shebang should be copied. I think always copying the shebang is potentially risky.

**Comment by HorlogeSkynet** [comment]
Fair enough, I'll try tomorrow to propagate one (or two ?) more parameter(s) from CLI to achieve that 👌

**Comment by HorlogeSkynet** [comment]
Updated !

**Comment by HorlogeSkynet** [comment]
Hey Michael ! What did you think about previously added changes ?
Thanks :bow:

**Comment by HorlogeSkynet** [comment]
Up again @mwilliamson !! (I even accidentally got a star on my fork :sweat_smile:)

Screenshot from 2020-07-13 16-02-14

**Comment by mwilliamson** [comment]
I've rebased and merged this change. The only tweak I made to the interface was to rename the argument to `--copy-shebang`. Thanks for the pull request!

**Comment by HorlogeSkynet** [comment]
Thanks Michael 🙇

**Pull request closed without merging**
