### PR TITLE
python3 and nested-package fixes

### PR DESCRIPTION
**Pull request by willjp**
Hello! Thanks very much for writing this tool!

I came across a couple of issues while using it which I made into a pull request.

1. I added parentheses to the print statement in the subprocess call in `stickytape.script()` 
2. subprocess's stdout returns a bytestring, which in python3 needed converting to a string.
3. I swapped `os.mkdir` with `os.makedirs` in prelude.py so that it could create packages of arbitrary depth.

Have a great day!

Will

### CODE REVIEW

**Comment by mwilliamson** [comment]
Thanks for the pull request. If you could provide test cases that currently fail, but pass with your changes, that'd be great.

**Comment by willjp** [comment]
oh sorry! Yes I will do that once I finish work. Thanks so much for the quick reply!

**Comment by mwilliamson** [comment]
Sorry for the slow response on this. Python 3 support should be fixed in the latest version, but I haven't had a chance to take a look at Windows support yet.

**Comment by mwilliamson** [comment]
Windows support should be working (or at least, working better!) now.

**Pull request closed without merging**
